name: Build Kernel H2OS
on:
  push:
    branches:    
      - makiras

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Init Repo
      run: |
        cd ~
        git clone https://github.com/yi985432/kernel_olive_lolz -b V11 --depth=1 
    - name: Build With Shell
      run: |
        cd ~/kernel_olive_lolz
        bash build_full.sh
    - name: Package With AnyKernel
      run: |
        cd ~
        cp kernel_olive_lolz/AnyKernel ./ -r
        cd AnyKernel/
        cp ../kernel_olive_lolz/out/arch/arm64/boot/Image.gz-dtb  ./

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: blu_spark_makiras_modified.zip
        path: /home/runner/AnyKernel/

